#!/bin/bash

echo "Running the moodle tests"

out=$(cat input1.txt | python3 main.py)

if [[ "$out" == "ABC-AB
5" ]]
then
    echo "Test1: Passed"
    let "count += 1"
else
    echo "Test1: Failed: "
    echo -ne "\tExpected:\tABC-AB 5\n"
    echo -ne "\tActual:  \t"
    echo $out 
fi
    
out=$(cat input2.txt | python3 main.py)

if [[ "$out" == "ABC*A-
5" ]]
then
    echo "Test2: Passed"
    let "count += 1"
else
    echo "Test2: Failed: "
    echo -ne "\tExpected:\tABC*A- 5\n"
    echo -ne "\tActual:  \t"
    echo $out
fi

out=$(cat input3.txt | python3 main.py)

if [[ "$out" == "ABC-A--B
5" ]]
then
    echo "Test3: Passed"
    let "count += 1"
else
    echo "Test3: Failed: "
    echo -ne "\tExpected:\tABC-A--B 5\n"
    echo -ne "\tActual:  \t"
    echo $out
fi

out=$(cat input4.txt | python3 main.py)

if [[ "$out" == "ABC-ABC*
7" ]]
then
    echo "Test4: Passed"
    let "count += 1"
else
    echo "Test4: Failed: "
    echo -ne "\tExpected:\tABC-ABC* 7\n"
    echo -ne "\tActual:  \t"
    echo $out
fi

out=$(cat input5.txt | python3 main.py)

if [[ "$out" == "ABC*AB-CA
8" ]]
then
    echo "Test5: Passed"
    let "count += 1"
else
    echo "Test5: Failed: "
    echo -ne "\tExpected:\tABC*AB-CA 8\n"
    echo -ne "\tActual:  \t"
    echo $out
fi

out=$(cat input6.txt | python3 main.py)

if [[ "$out" == "AB-C-A-
4" ]]
then
    echo "Test6: Passed"
    let "count += 1"
else
    echo "Test6: Failed: "
    echo -ne "\tExpected:\tAB-C-A- 4\n"
    echo -ne "\tActual:  \t"
    echo $out
fi

out=$(cat input7.txt | python3 main.py)

if [[ "$out" == "ABC*-B--CB
7" ]]
then
    echo "Test7: Passed"
    let "count += 1"
else
    echo "Test7: Failed: "
    echo -ne "\tExpected:\tABC*-B--CB 7\n"
    echo -ne "\tActual:  \t"
    echo $out
fi

echo -n $count
echo "/7"
